pipelines:
  default:
    - step:
        name: Install and Build
        image: node:16
        script:
          - yarn install
          - yarn build
          - zip -r dist.zip .next package.json package-lock.json
    - step:
        name: Deploy to Azure
        script:
          - pipe: microsoft/azure-web-apps-deploy:1.0.2
            variables:
              AZURE_APP_ID: '47140a82-b1f2-4c35-83a1-0fbd59c73e53'
              AZURE_PASSWORD: 'mye8Q~m5S-vz~pXbJBWyMzgGQvzp2f8hxbEGVbRY'
              AZURE_TENANT_ID: '2075dd1a-d2b7-4e5a-b023-ef78ca875fa7'
              AZURE_RESOURCE_GROUP: 'TestingkreatesellDEV'
              AZURE_APP_NAME: 'devKreatesell'
              ZIP_FILE: 'dist.zip'
