[build]
publish = ".next"
command = "npm run build"
functions = ".next/functions"
# Add this line to use _redirects file
redirects = "_redirects"

# Image redirect
[[redirects]]
  from = "/images/*"
  to = "/_next/static/images/:splat"
