[build]
publish = ".next/server"
command = "npm run build"
functions = ".next/functions"

[[redirects]]
  from = "/*"
  to = "/.next/server/pages/:splat"
  status = 200
  redirects = "_redirects"

[[redirects]]
  from = "/images/*"
  to = "/next/static/image/public/images/:splat"
  status = 200