export const AFFILIATE_PRODUCTS_REQUEST = "AFFILIATE_PRODUCTS_REQUEST";
export const AFFILIATE_PRODUCTS_SUCCESS = "AFFILIATE_PRODUCTS_SUCCESS";
export const AFFILIATE_PRODUCTS_FAILURE = "AFFILIATE_PRODUCTS_FAILURE";
