// import { generateActions } from "../../utils";
// export const GET_NOTIFICATIONS = generateActions("GET_NOTIFICATIONS");
// export const READ_NOTIFICATIONS = generateActions("READ_NOTIFICATIONS");

export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAILURE = "GET_NOTIFICATIONS_FAILURE";
