export const questions = [
    {
        question: "If the product bought is not genuine, can I get a refund?", 
        answer:"Yes, you can request a refund within 30 days of purchase if the product has a refund policy attached."
    },
    {
        question: "How do I request a refund if I don’t want a product I bought anymore?", 
        answer:"Kreatesell is an easy-to-use, cross-border education technology (edtech) SaaS platform that enables content kreators and digital entrepreneurs to upload their digital products for the fastest and easiest sales. With KreateSell, you can convert your audience into buying customers without going through the stress of learning many sales funnels that may be complex to use. Also, you instantly get paid from anywhere in the world conveniently. See more about how it works. Kreatesell is solving the major problems that Kreators face while selling online including having no means to receive payment in foreign currency. With Kreatesell, this is no longer a barrier because buyers can now pay in their local currency and Kreators can receive the money seamlessly in their local currencies without going through the stress of trying to exchange currencies using third-party platforms. On Kreatesell, you have access to a large number of affiliates ready to promote your product to potential buyers with a preset commission fee of your choice. Also, you do not have to go through the stress of manual delivery of your digital product, your delivery process is automated for you. Your customer receives the product immediately after payment is confirmed."
    },
    {
        question: "How safe is it to make payment with my card on your website?", 
        answer:"Kreatesell is an easy-to-use, cross-border education technology (edtech) SaaS platform that enables content kreators and digital entrepreneurs to upload their digital products for the fastest and easiest sales. With KreateSell, you can convert your audience into buying customers without going through the stress of learning many sales funnels that may be complex to use. Also, you instantly get paid from anywhere in the world conveniently. See more about how it works. Kreatesell is solving the major problems that Kreators face while selling online including having no means to receive payment in foreign currency. With Kreatesell, this is no longer a barrier because buyers can now pay in their local currency and Kreators can receive the money seamlessly in their local currencies without going through the stress of trying to exchange currencies using third-party platforms. On Kreatesell, you have access to a large number of affiliates ready to promote your product to potential buyers with a preset commission fee of your choice. Also, you do not have to go through the stress of manual delivery of your digital product, your delivery process is automated for you. Your customer receives the product immediately after payment is confirmed."
    },
    {
        question: "How does the bank transfer payment option work?", 
        answer:"Kreatesell is an easy-to-use, cross-border education technology (edtech) SaaS platform that enables content kreators and digital entrepreneurs to upload their digital products for the fastest and easiest sales. With KreateSell, you can convert your audience into buying customers without going through the stress of learning many sales funnels that may be complex to use. Also, you instantly get paid from anywhere in the world conveniently. See more about how it works. Kreatesell is solving the major problems that Kreators face while selling online including having no means to receive payment in foreign currency. With Kreatesell, this is no longer a barrier because buyers can now pay in their local currency and Kreators can receive the money seamlessly in their local currencies without going through the stress of trying to exchange currencies using third-party platforms. On Kreatesell, you have access to a large number of affiliates ready to promote your product to potential buyers with a preset commission fee of your choice. Also, you do not have to go through the stress of manual delivery of your digital product, your delivery process is automated for you. Your customer receives the product immediately after payment is confirmed."
    },
    {
        question: "How am I sure about the quality of products on your platform?", 
        answer:"Kreatesell is an easy-to-use, cross-border education technology (edtech) SaaS platform that enables content kreators and digital entrepreneurs to upload their digital products for the fastest and easiest sales. With KreateSell, you can convert your audience into buying customers without going through the stress of learning many sales funnels that may be complex to use. Also, you instantly get paid from anywhere in the world conveniently. See more about how it works. Kreatesell is solving the major problems that Kreators face while selling online including having no means to receive payment in foreign currency. With Kreatesell, this is no longer a barrier because buyers can now pay in their local currency and Kreators can receive the money seamlessly in their local currencies without going through the stress of trying to exchange currencies using third-party platforms. On Kreatesell, you have access to a large number of affiliates ready to promote your product to potential buyers with a preset commission fee of your choice. Also, you do not have to go through the stress of manual delivery of your digital product, your delivery process is automated for you. Your customer receives the product immediately after payment is confirmed."
    },
    {
        question: "How do I download a product I paid for?", 
        answer:"Kreatesell is an easy-to-use, cross-border education technology (edtech) SaaS platform that enables content kreators and digital entrepreneurs to upload their digital products for the fastest and easiest sales. With KreateSell, you can convert your audience into buying customers without going through the stress of learning many sales funnels that may be complex to use. Also, you instantly get paid from anywhere in the world conveniently. See more about how it works. Kreatesell is solving the major problems that Kreators face while selling online including having no means to receive payment in foreign currency. With Kreatesell, this is no longer a barrier because buyers can now pay in their local currency and Kreators can receive the money seamlessly in their local currencies without going through the stress of trying to exchange currencies using third-party platforms. On Kreatesell, you have access to a large number of affiliates ready to promote your product to potential buyers with a preset commission fee of your choice. Also, you do not have to go through the stress of manual delivery of your digital product, your delivery process is automated for you. Your customer receives the product immediately after payment is confirmed."
    },
    {
        question: "I just bought a product on Kreatesell, can I also sell a product I own?", 
        answer:"Kreatesell is an easy-to-use, cross-border education technology (edtech) SaaS platform that enables content kreators and digital entrepreneurs to upload their digital products for the fastest and easiest sales. With KreateSell, you can convert your audience into buying customers without going through the stress of learning many sales funnels that may be complex to use. Also, you instantly get paid from anywhere in the world conveniently. See more about how it works. Kreatesell is solving the major problems that Kreators face while selling online including having no means to receive payment in foreign currency. With Kreatesell, this is no longer a barrier because buyers can now pay in their local currency and Kreators can receive the money seamlessly in their local currencies without going through the stress of trying to exchange currencies using third-party platforms. On Kreatesell, you have access to a large number of affiliates ready to promote your product to potential buyers with a preset commission fee of your choice. Also, you do not have to go through the stress of manual delivery of your digital product, your delivery process is automated for you. Your customer receives the product immediately after payment is confirmed."
    },
]