import {
  NgFlag,
  UsFlag,
  UkFlag,
  GhFlag,
  KenFlag,
  UganFlag,
  SouthAfricanFlag,
  LiberianFlag,
  TanzanianFlag,
  LeoneFlag,
  MalawiFlag,
  BeninFlag,
  GambianFlag,
  IvoryCoastFlag,
  TogoFlag,
  SenegalFlag,
  MaliFlag,
  BurnkinaFasoFlag,
  ChadFlag,
  GabonFlag,
  CamFlag,
} from "utils";

export { NgFlag as Flag };

export const data = [
  { currency: "NGN", country: "Nigeria", flag: <NgFlag /> },
  { currency: "", country: "USA", flag: <UsFlag /> },
  { currency: "", country: "United kingdom", flag: <UkFlag /> },
  { currency: "", country: "Ghana", flag: <GhFlag /> },
  { currency: "", country: "Kenya", flag: <KenFlag /> },
  { currency: "", country: "Uganda", flag: <UganFlag /> },
  { currency: "", country: "South Africa", flag: <SouthAfricanFlag /> },
  { currency: "", country: "Burkina Faso", flag: <BurnkinaFasoFlag /> },
  { currency: "", country: "Liberia", flag: <LiberianFlag /> },
  { currency: "", country: "Tanzania", flag: <TanzanianFlag /> },
  { currency: "", country: "Sierra Leone", flag: <LeoneFlag /> },
  { currency: "", country: "Malawi", flag: <MalawiFlag /> },
  { currency: "", country: "Benin Republic", flag: <BeninFlag /> },
  { currency: "", country: "Gambia", flag: <GambianFlag /> },
  { currency: "", country: "Ivory Coast", flag: <IvoryCoastFlag /> },
  { currency: "", country: "Togo", flag: <TogoFlag /> },
  { currency: "", country: "Senegal", flag: <SenegalFlag /> },
  { currency: "", country: "Mali", flag: <MaliFlag /> },
  { currency: "", country: "Chad", flag: <ChadFlag /> },
  { currency: "", country: "Cameroon", flag: <CamFlag /> },
  { currency: "", country: "Gabon", flag: <GabonFlag /> },
];
