import {
  NgFlag,
  UsFlag,
  UkFlag,
  GhFlag,
  KenFlag,
  UganFlag,
  SouthAfricanFlag,
  LiberianFlag,
  TanzanianFlag,
  LeoneFlag,
  MalawiFlag,
  BeninFlag,
  GambianFlag,
  IvoryCoastFlag,
  TogoFlag,
  SenegalFlag,
  MaliFlag,
  BurnkinaFasoFlag,
  ChadFlag,
  GabonFlag,
  CamFlag,
} from "utils";

export { BurnkinaFasoFlag as Flag };

export const data = [
  { currency: "NGN", country: "Nigeria", flag: NgFlag?.src },
  { currency: "", country: "USA", flag: UsFlag?.src },
  { currency: "", country: "United kingdom", flag: UkFlag?.src },
  { currency: "", country: "Ghana", flag: GhFlag?.src },
  { currency: "", country: "Kenya", flag: KenFlag?.src },
  { currency: "", country: "Uganda", flag: UganFlag?.src },
  { currency: "", country: "South Africa", flag: SouthAfricanFlag?.src },
  { currency: "", country: "Burkina Faso", flag: BurnkinaFasoFlag?.src },
  { currency: "", country: "Liberia", flag: LiberianFlag?.src },
  { currency: "", country: "Tanzania", flag: TanzanianFlag?.src },
  { currency: "", country: "Sierra Leone", flag: LeoneFlag?.src },
  { currency: "", country: "Malawi", flag: MalawiFlag?.src },
  { currency: "", country: "Benin Republic", flag: BeninFlag?.src },
  { currency: "", country: "Gambia", flag: GambianFlag?.src },
  { currency: "", country: "Ivory Coast", flag: IvoryCoastFlag?.src },
  { currency: "", country: "Togo", flag: TogoFlag?.src },
  { currency: "", country: "Senegal", flag: SenegalFlag?.src },
  { currency: "", country: "Mali", flag: MaliFlag?.src },
  { currency: "", country: "Chad", flag: ChadFlag?.src },
  { currency: "", country: "Cameroon", flag: CamFlag?.src },
  { currency: "", country: "Gabon", flag: GabonFlag?.src },
];

// export const data = [
//   { currency: "NGN", country: "Nigeria", flag: NgFlag?.src },
//   { currency: "", country: "USA", flag: UsFlag?.src },
//   { currency: "", country: "United kingdom", flag: UkFlag?.src },
//   { currency: "", country: "Ghana", flag: GhFlag?.src },
//   { currency: "", country: "Kenya", flag: KenFlag?.src },
//   { currency: "", country: "Uganda", flag: UganFlag?.src },
//   { currency: "", country: "South Africa", flag: SouthAfricanFlag?.src },
//   { currency: "", country: "Burkina Faso", flag: BurnkinaFasoFlag?.src },
//   { currency: "", country: "Liberia", flag: LiberianFlag?.src },
//   { currency: "", country: "Tanzania", flag: TanzanianFlag?.src },
//   { currency: "", country: "Sierra Leone", flag: LeoneFlag?.src },
//   { currency: "", country: "Malawi", flag: MalawiFlag?.src },
//   { currency: "", country: "Benin Republic", flag: BeninFlag?.src },
//   { currency: "", country: "Gambia", flag: GambianFlag?.src },
//   { currency: "", country: "Ivory Coast", flag: IvoryCoastFlag?.src },
//   { currency: "", country: "Togo", flag: TogoFlag?.src },
//   { currency: "", country: "Senegal", flag: SenegalFlag?.src },
//   { currency: "", country: "Mali", flag: MaliFlag?.src },
//   { currency: "", country: "Chad", flag: ChadFlag?.src },
//   { currency: "", country: "Cameroon", flag: CamFlag?.src },
//   { currency: "", country: "Gabon", flag: GabonFlag?.src },
// ];
