export const mockData = [
  {
    id: "12",
    product_name: "Complete Facials",
    product_description: "Complete facials for woman",
    enable_preorder: "False",
    preoder_date: "",
    upload_content: "False",
    is_preoder_downloadable: "False",
    is_redirect_buyer: "False",
    product_visibility: "1",
    is_preview_only: "False",
    product_cover_picture: "",
    status: "3",
    is_active: "True",
    is_allow_affiliate: "True",
    affiliate_percentage_on_sales: "0",
    is_limited_sales: "True",
    number_of_product: "0",
    is_show_number_of_sales: "True",
    user_id: "1d3a15f6-762c-4bf0-a78f-0694e8ab7eef",
    date_created: "10/11/2021 8:25:21 PM",
    date_updated: "10/11/2021 8:47:51 PM",
    selling_price: "0.00",
    original_price: "0.00",
    product_type_id: "3",
    kreasell_product_id: "KREATE-undefined637695807219666972",
    product_listing_status: "1",
    cta_button: "BUY NOW",
    who_bears_fee: "customer",
    minimum_price: "0.00",
    is_minimum_price: "False",
    is_show_compare_price: "False",
    billing_interval_id: "0",
    pricing_type_id: "1",
    is_strike_original_price: "False",
    billing_frequency: "0",
    start_date: "",
    end_date: "",
  },
  {
    id: "13",
    product_name: "Moulding Techniques",
    product_description: "Techniques to mould client into a narrative",
    enable_preorder: "False",
    preoder_date: "",
    upload_content: "False",
    is_preoder_downloadable: "False",
    is_redirect_buyer: "False",
    product_visibility: "0",
    is_preview_only: "False",
    product_cover_picture: "",
    status: "1",
    is_active: "true",
    is_allow_affiliate: "True",
    affiliate_percentage_on_sales: "0",
    is_limited_sales: "True",
    number_of_product: "0",
    is_show_number_of_sales: "True",
    user_id: "e1718cad-000a-41b7-99a4-af0c515aae57",
    date_created: "10/12/2021 9:38:21 AM",
    date_updated: "10/12/2021 9:38:21 AM",
    selling_price: "0.00",
    original_price: "0.00",
    product_type_id: "3",
    kreasell_product_id: "KREATE-Goks Store637696283020607552",
    product_listing_status: "1",
    cta_button: "BUY NOW",
    who_bears_fee: "customer",
    minimum_price: "0.00",
    is_minimum_price: "False",
    is_show_compare_price: "False",
    billing_interval_id: "0",
    pricing_type_id: "1",
    is_strike_original_price: "False",
    billing_frequency: "0",
    start_date: "",
    end_date: "",
  },
  {
    id: "16",
    product_name: "Digital item3",
    product_description: "Digital Data Description yeast",
    enable_preorder: "True",
    preoder_date: "10/25/2021 5:21:06 PM",
    upload_content: "False",
    is_preoder_downloadable: "True",
    is_redirect_buyer: "False",
    product_visibility: "2",
    is_preview_only: "False",
    product_cover_picture:
      "https://res.cloudinary.com/salvoagency/image/upload/v1635014984/kreatesell/productimages/ynqyw9rcih1hydhtets0.jpg",
    status: "1",
    is_active: "True",
    is_allow_affiliate: "",
    affiliate_percentage_on_sales: "",
    is_limited_sales: "",
    number_of_product: "0",
    is_show_number_of_sales: "",
    user_id: "e1718cad-000a-41b7-99a4-af0c515aae57",
    date_created: "10/23/2021 6:49:45 PM",
    date_updated: "",
    selling_price: "0.00",
    original_price: "",
    product_type_id: "1",
    kreasell_product_id: "KREATE-moulders637706117856727450",
    product_listing_status: "1",
    cta_button: "BUY NOW",
    who_bears_fee: "customer",
    minimum_price: "0.00",
    is_minimum_price: "False",
    is_show_compare_price: "False",
    billing_interval_id: "1",
    pricing_type_id: "1",
    is_strike_original_price: "False",
    billing_frequency: "0",
    start_date: "",
    end_date: "",
  },
  {
    id: "18",
    product_name: "Digital item 56",
    product_description: "Digital Data Description for 56",
    enable_preorder: "True",
    preoder_date: "10/25/2021 5:21:06 PM",
    upload_content: "False",
    is_preoder_downloadable: "True",
    is_redirect_buyer: "False",
    product_visibility: "2",
    is_preview_only: "False",
    product_cover_picture:
      "https://res.cloudinary.com/salvoagency/image/upload/v1635015462/kreatesell/productimages/v7do9fburhtp9jeotltm.jpg",
    status: "1",
    is_active: "True",
    is_allow_affiliate: "",
    affiliate_percentage_on_sales: "",
    is_limited_sales: "",
    number_of_product: "0",
    is_show_number_of_sales: "",
    user_id: "e1718cad-000a-41b7-99a4-af0c515aae57",
    date_created: "10/23/2021 6:57:43 PM",
    date_updated: "",
    selling_price: "0.00",
    original_price: "",
    product_type_id: "1",
    kreasell_product_id: "KREATE-moulders637706122636890342",
    product_listing_status: "1",
    cta_button: "BUY NOW",
    who_bears_fee: "customer",
    minimum_price: "0.00",
    is_minimum_price: "False",
    is_show_compare_price: "False",
    billing_interval_id: "1",
    pricing_type_id: "1",
    is_strike_original_price: "False",
    billing_frequency: "0",
    start_date: "",
    end_date: "",
  },
  {
    id: "19",
    product_name: "Digital item 5556",
    product_description: "Digital Data Description for 56",
    enable_preorder: "True",
    preoder_date: "10/25/2021 5:21:06 PM",
    upload_content: "False",
    is_preoder_downloadable: "True",
    is_redirect_buyer: "False",
    product_visibility: "2",
    is_preview_only: "False",
    product_cover_picture:
      "https://res.cloudinary.com/salvoagency/image/upload/v1635015527/kreatesell/productimages/fyfwkdxvcfets2ie5hjc.jpg",
    status: "1",
    is_active: "true",
    is_allow_affiliate: "",
    affiliate_percentage_on_sales: "",
    is_limited_sales: "",
    number_of_product: "0",
    is_show_number_of_sales: "",
    user_id: "e1718cad-000a-41b7-99a4-af0c515aae57",
    date_created: "10/23/2021 6:58:48 PM",
    date_updated: "",
    selling_price: "0.00",
    original_price: "",
    product_type_id: "1",
    kreasell_product_id: "KREATE-moulders637706123282724739",
    product_listing_status: "1",
    cta_button: "BUY NOW",
    who_bears_fee: "customer",
    minimum_price: "0.00",
    is_minimum_price: "False",
    is_show_compare_price: "False",
    billing_interval_id: "1",
    pricing_type_id: "1",
    is_strike_original_price: "False",
    billing_frequency: "0",
    start_date: "",
    end_date: "",
  },
  {
    id: "21",
    product_name: "Digital monogram 6",
    product_description: "Digital Data Description for 56",
    enable_preorder: "True",
    preoder_date: "10/25/2021 5:21:06 PM",
    upload_content: "False",
    is_preoder_downloadable: "True",
    is_redirect_buyer: "False",
    product_visibility: "2",
    is_preview_only: "False",
    product_cover_picture:
      "https://res.cloudinary.com/salvoagency/image/upload/v1635015628/kreatesell/productimages/ykyej6cudp3es06qqezx.jpg",
    status: "1",
    is_active: "true",
    is_allow_affiliate: "",
    affiliate_percentage_on_sales: "",
    is_limited_sales: "",
    number_of_product: "0",
    is_show_number_of_sales: "",
    user_id: "e1718cad-000a-41b7-99a4-af0c515aae57",
    date_created: "10/23/2021 7:00:30 PM",
    date_updated: "",
    selling_price: "0.00",
    original_price: "",
    product_type_id: "1",
    kreasell_product_id: "KREATE-moulders637706124305962801",
    product_listing_status: "1",
    cta_button: "BUY NOW",
    who_bears_fee: "customer",
    minimum_price: "0.00",
    is_minimum_price: "False",
    is_show_compare_price: "False",
    billing_interval_id: "1",
    pricing_type_id: "1",
    is_strike_original_price: "False",
    billing_frequency: "0",
    start_date: "",
    end_date: "",
  },
];
