export const ProductsTableData = [
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "live",
		id: 1,
	},
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "draft",
		id: 2,
	},
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "deactivated",
		id: 3,
	},
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "flagged",
		id: 4,
	},
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "revoked",
		id: 5,
	},
];
