export const ProductsTableData = [
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "live",
	},
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "draft",
	},
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "deactivated",
	},
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "flagged",
	},
	{
		Product: "Air Jordan",
		ProductLink: "https://kreatesell.com//the-land-of-hope-and-opportunities",
		ProductType: "Physical Product",
		Price: 5000,
		createdAt: "June 12th, 2021",
		status: "revoked",
	},
];
