export const statusArr = [
  { type: "All", label: "All" },
  { type: "Pending", label: "Pending" },
  { type: "Approved", label: "Approved" },
  { type: "Denied", label: "Denied" },
];

export const requestsData = [
  {
    id: 1,
    affiliate: "Adeyemi Samuel",
    product: "Product Name",
    product_type: 3,
    date_created: "2021-12-13",
    sales: 12,
    notes: "This is a note",
    notes_read: true,
    status: "Approved",
  },
  {
    id: 2,
    affiliate: "Mary Jane",
    product: "Coding Tutorial",
    product_type: 1,
    date_created: "2022-1-11",
    sales: 5,
    notes: "This is a note",
    notes_read: false,
    status: "Declined",
  },
  {
    id: 3,
    affiliate: "Paul Jones",
    product: "Testing Testing",
    product_type: 2,
    date_created: "2021-3-5",
    sales: 1,
    notes: "This is a note",
    notes_read: true,
    status: "Approved",
  },
  {
    id: 4,
    affiliate: "Peter Pan",
    product: "The Role of Coding in Engineering",
    product_type: 3,
    date_created: "2021-12-25",
    sales: 25,
    notes: "This is a note",
    notes_read: false,
    status: "Revoked",
  },
  {
    id: 5,
    affiliate: "Peter Parker",
    product: "Hello World",
    product_type: 1,
    date_created: "2021-10-1",
    sales: 5,
    notes: "This is a note",
    notes_read: true,
    status: "Approved",
  },
  {
    id: 6,
    affiliate: "Sun Tzu",
    product: "The Art of War",
    product_type: 2,
    date_created: "2020-5-27",
    sales: 1000,
    notes: "This is a note",
    notes_read: true,
    status: "Approved",
  },
  {
    id: 7,
    affiliate: "Pete Aurelio",
    product: "Maxim Maxima",
    product_type: 3,
    date_created: "2022-1-11",
    sales: 30,
    notes: "This is a note",
    notes_read: true,
    status: "Declined",
  },
  {
    id: 8,
    affiliate: "Dean Winchester",
    product: "Console Dot Log",
    product_type: 2,
    date_created: "2022-2-14",
    sales: 2500,
    notes: "This is a note",
    notes_read: true,
    status: "Revoked",
  },
];
