export const statusArr = [
  { type: "All", label: "All" },
  { type: "Pending", label: "Pending" },
  { type: "Approved", label: "Approved" },
  { type: "Denied", label: "Denied" },
];

export const requestsData = [
  {
    id: 1,
    affiliate_name: "Adeyemi Samuel",
    product_name: "Product Name",
    product_type_id: 3,
    date_created: "2021-12-13",
    number_of_sales: 12,
    notes: "This is a note",
    notes_read: true,
    status: "Approved",
    reported: true,
  },
  {
    id: 2,
    affiliate_name: "Mary Jane",
    product_name: "Coding Tutorial",
    product_type_id: 1,
    date_created: "2022-1-11",
    number_of_sales: 5,
    notes: "This is a note",
    notes_read: false,
    status: "Declined",
    reported: false,
  },
  {
    id: 3,
    affiliate_name: "Paul Jones",
    product_name: "Testing Testing",
    product_type_id: 2,
    date_created: "2021-3-5",
    number_of_sales: 1,
    notes: "This is a note",
    notes_read: true,
    status: "Approved",
    reported: false,
  },
  {
    id: 4,
    affiliate_name: "Peter Pan",
    product_name: "The Role of Coding in Engineering",
    product_type_id: 3,
    date_created: "2021-12-25",
    number_of_sales: 25,
    notes: "This is a note",
    notes_read: false,
    status: "Revoked",
    reported: false,
  },
  {
    id: 5,
    affiliate_name: "Peter Parker",
    product_name: "Hello World",
    product_type_id: 1,
    date_created: "2021-10-1",
    number_of_sales: 5,
    notes: "This is a note",
    notes_read: true,
    status: "Approved",
    reported: false,
  },
  {
    id: 6,
    affiliate_name: "Sun Tzu",
    product_name: "The Art of War",
    product_type_id: 2,
    date_created: "2020-5-27",
    number_of_sales: 1000,
    notes: "This is a note",
    notes_read: true,
    status: "Approved",
    reported: true,
  },
  {
    id: 7,
    affiliate_name: "Pete Aurelio",
    product_name: "Maxim Maxima",
    product_type_id: 3,
    date_created: "2022-1-11",
    number_of_sales: 30,
    notes: "This is a note",
    notes_read: true,
    status: "Declined",
    reported: false,
  },
  {
    id: 8,
    affiliate_name: "Dean Winchester",
    product_name: "Console Dot Log",
    product_type_id: 2,
    date_created: "2022-2-14",
    number_of_sales: 2500,
    notes: "This is a note",
    notes_read: true,
    status: "Revoked",
    reported: false,
  },
];
