import {
  IntZoom,
  IntCoinBase,
  IntSamsungPay,
  IntApplePay,
  IntGooglePay,
  IntFacebookPixels,
  IntGoogleAnalytics,
  IntHoverSignal,
  IntZapier,
  IntGoToWebinar,
  IntGetResponse,
  IntMailChimp,
  IntAwebber,
} from "utils";
